### PR TITLE
[WIP] fixes

### LINKED ISSUE #86: Required fields
@kamicut I think you may have already closed this ticket so am writing another. Issues are:

There are fields that **shouldn't be required** because they don't happen all the time. These are: 
       - All Arabic labels should not be required
       - Project Amendments
       - Project delays
       - Implementing Partners
       - Disbursed funds because we don't always have this information

Ones that should be required: 
       - Project Status
       - PLANNED START DATE
       - ACTUAL START DATE 

This is all I have for right now

Thanks!

### PR DESCRIPTION
**Pull request by kamicut**
Includes work from #85 and additionally closes #86 and #87

### CODE REVIEW

**Comment by felskia** [comment]
@kamicut there is tons of stuff that says it's required but it isn't actually required. 

Also, please make sure there are * required markers on ones that are. For example planned project start and end dates. 

screen shot 2017-01-17 at 5 27 00 pm

**Comment by kamicut** [comment]
@felskia I'll work on adding the * to the names. Which ones aren't required, I'm following #86?

**Comment by felskia** [comment]
@kamicut I'll make a full list but it's all listed there. Or a combined list

**Comment by felskia** [comment]
@kamicut 

- objective is required but doesn't have a *
- same with project status
- planned start and end date
- Number of beneficiaries should have next to each field (except for the arabic title)
- Same with SDS and SDG
- Same with sub-sector
- and Governorate on the locations
- Currency items in budget

**Comment by felskia** [comment]
All fields including, required fields, some required fields that don't even have an error, and some non-required fields all turn red when pressing submit.

**Pull request merged**
